import { ChapterDefinition } from "../engine/narrative/types";

export const CHAPTERS: ChapterDefinition[] = [
  {
    id: "chapter-1",
    title: "New Beginnings",
    objectives: [
      {
        id: "explore_home",
        description: "Explore your personal files",
        check: { source: "storyFlag", key: "read_resume" },
        optional: true,
      },
      {
        id: "learn_linux_basics",
        description: "Learn basic Linux commands",
        check: { source: "storyFlag", key: "basic_tools_unlocked" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "basic_tools_unlocked" },
        optional: true,
      },
      {
        id: "fix_backup",
        description: "Fix the backup script",
        check: { source: "storyFlag", key: "fixed_backup_script" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_cron_backup" },
        optional: true,
      },
      {
        id: "run_auto_apply",
        description: "Run the job application script",
        check: { source: "storyFlag", key: "ran_auto_apply" },
        optional: true,
      },
      {
        id: "check_email",
        description: "Check your email",
        check: { source: "storyFlag", key: "read_nexacorp_offer" },
      },
      {
        id: "check_piper",
        description: "Check Piper for messages",
        check: { source: "completedObjective", key: "piper_checked" },
        optional: true,
      },
      {
        id: "accept_offer",
        description: "Accept the job offer",
        check: { source: "completedObjective", key: "accepted_nexacorp" },
        failCheck: { source: "completedObjective", key: "rejected_nexacorp_final" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_nexacorp_offer" },
      },
      {
        id: "read_chip_setup",
        description: "Read Chip's setup email",
        check: { source: "storyFlag", key: "ssh_unlocked" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "accepted_nexacorp" },
      },
      {
        id: "first_ssh_connect",
        description: "SSH into NexaCorp to start work",
        check: { source: "storyFlag", key: "first_ssh_connect" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "ssh_unlocked" },
      },

      // Quest 1: Olive's Terminal Challenges
      {
        id: "olive_challenges",
        description: "Olive's Terminal Challenges",
        check: { source: "allVisibleChildren" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "olive_challenges_read" },
      },
      {
        id: "olive_ch_file",
        description: "Identify a file type with file",
        check: { source: "storyFlag", key: "used_file_in_downloads" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "olive_challenges_read" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_which",
        description: "Find where Python lives",
        check: { source: "storyFlag", key: "used_which_python" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "used_file_in_downloads" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_projects",
        description: "Create a Projects folder",
        check: { source: "storyFlag", key: "created_projects_dir" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "used_which_python" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_mv",
        description: "Rename a file with mv",
        check: { source: "storyFlag", key: "used_mv_home" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "created_projects_dir" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_echo",
        description: "Pipe or redirect echo output",
        check: { source: "storyFlag", key: "used_echo_pipe" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "used_mv_home" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_man",
        description: "Read a manual page",
        check: { source: "storyFlag", key: "used_man_command" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "used_echo_pipe" },
        group: "olive_challenges",
      },

      // Quest 2: Fix & Extend Backup
      {
        id: "backup_quest",
        description: "Fix & Extend Backup",
        check: { source: "allVisibleChildren" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
      },
      {
        id: "backup_mkdir",
        description: "Create a backup directory",
        check: { source: "storyFlag", key: "created_backups_dir" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
        group: "backup_quest",
      },
      {
        id: "backup_copy",
        description: "Copy your scripts to the backup",
        check: { source: "storyFlag", key: "copied_scripts_backup" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
        group: "backup_quest",
      },
      {
        id: "backup_log",
        description: "Log the backup result",
        check: { source: "storyFlag", key: "created_backup_log" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
        group: "backup_quest",
      },
      {
        id: "backup_verify",
        description: "Verify the backup with file",
        check: { source: "storyFlag", key: "verified_backup" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
        group: "backup_quest",
      },
    ],
  },
  {
    id: "chapter-2",
    title: "First Day",
    objectives: [
      {
        id: "read_welcome_email",
        description: "Read Edward's welcome email",
        check: { source: "storyFlag", key: "piper_unlocked" },
      },
      {
        id: "edward_onboarding",
        description: "Edward's Onboarding",
        check: { source: "allVisibleChildren" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "read_welcome_email" },
      },
      {
        id: "read_onboarding",
        description: "Read the onboarding docs",
        check: { source: "storyFlag", key: "read_onboarding" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "read_welcome_email" },
        group: "edward_onboarding",
      },
      {
        id: "meet_the_team",
        description: "Read the team directory",
        check: { source: "storyFlag", key: "read_team_info" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "read_welcome_email" },
        group: "edward_onboarding",
      },
      {
        id: "reply_edward_chip_intro",
        description: "Reply to Edward on Piper",
        check: { source: "completedObjective", key: "replied_edward_chip_intro" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_team_info" },
        group: "edward_onboarding",
      },
      {
        id: "try_chip",
        description: "Try running Chip",
        check: { source: "storyFlag", key: "chip_error_seen" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "chip_unlocked" },
        group: "edward_onboarding",
      },
      {
        id: "tell_edward_chip_error",
        description: "Message Edward about the error",
        check: { source: "completedObjective", key: "told_edward_chip_error" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "chip_error_seen" },
        group: "edward_onboarding",
      },
      {
        id: "source_zshrc",
        description: "Reload your shell config",
        check: { source: "storyFlag", key: "sourced_nexacorp_zshrc" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "printenv_unlocked" },
        group: "edward_onboarding",
      },
      {
        id: "help_oscar_logs",
        description: "Help Oscar with logs",
        check: { source: "completedObjective", key: "oscar_access_reported" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_onboarding" },
      },
      {
        id: "meet_auri",
        description: "Meet Auri",
        check: { source: "completedObjective", key: "auri_dbt_reported" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "piper_unlocked" },
      },
{
        id: "review_handoff",
        description: "Review Jin Chen's handoff notes",
        check: { source: "storyFlag", key: "read_handoff_notes" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "reply_auri_handoff",
        description: "Message Auri about the handoff notes",
        check: { source: "completedObjective", key: "handoff_reviewed" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_handoff_notes" },
        group: "meet_auri",
      },
      {
        id: "help_auri_pipeline",
        description: "Get familiar with the data pipeline",
        check: { source: "storyFlag", key: "ran_dbt" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "handoff_reviewed" },
        group: "meet_auri",
      },
      {
        id: "clone_analytics_repo",
        description: "Clone nexacorp-analytics",
        check: { source: "storyFlag", key: "dbt_project_cloned" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "help_auri_pipeline" },
        group: "meet_auri",
      },
      {
        id: "run_dbt",
        description: "Run a full pipeline build",
        check: { source: "storyFlag", key: "ran_dbt" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "clone_analytics_repo" },
        group: "meet_auri",
      },
      {
        id: "check_auri_dbt",
        description: "Check in with Auri about the build",
        check: { source: "completedObjective", key: "auri_dbt_reported" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "run_dbt" },
        group: "meet_auri",
      },
      // Bridging objective: prompt player to check email
      {
        id: "check_eod_email",
        description: "Check your email",
        check: { source: "storyFlag", key: "read_end_of_day" },
        hidden: true,
        visibleWhen: { source: "deliveredEmail", key: "edward_end_of_day" },
      },
      // Closing Time quest group
      {
        id: "closing_time",
        description: "Closing Time",
        check: { source: "allVisibleChildren" },
        hidden: true,
        visibleWhen: { source: "deliveredEmail", key: "edward_end_of_day" },
      },
      {
        id: "read_eod_email",
        description: "Read Edward's end-of-day email",
        check: { source: "storyFlag", key: "read_end_of_day" },
        hidden: true,
        visibleWhen: { source: "deliveredEmail", key: "edward_end_of_day" },
        group: "closing_time",
      },
      {
        id: "head_home",
        description: "Head home for the day",
        check: { source: "storyFlag", key: "returned_home_day1" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_end_of_day" },
        group: "closing_time",
      },
      {
        id: "read_piper_home",
        description: "Read your Piper messages at home",
        check: { source: "storyFlag", key: "read_piper_day1_home" },
        optional: true,
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "returned_home_day1" },
      },
      {
        id: "shutdown_day1",
        description: "Shut down your PC",
        check: { source: "storyFlag", key: "day1_shutdown" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "returned_home_day1" },
        group: "closing_time",
      },
      {
        id: "oscar_search_logs",
        description: "Search the system logs for errors",
        check: { source: "storyFlag", key: "oscar_searched_logs" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
        group: "help_oscar_logs",
      },
      {
        id: "oscar_check_backups",
        description: "Check the backup logs",
        check: { source: "storyFlag", key: "oscar_checked_backups" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
        group: "help_oscar_logs",
      },
      {
        id: "oscar_diff_logs",
        description: "Diff the active and backup logs",
        check: { source: "storyFlag", key: "oscar_diffed_logs" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
        group: "help_oscar_logs",
      },
      {
        id: "reply_oscar_logs",
        description: "Report system log findings to Oscar",
        check: { source: "completedObjective", key: "oscar_log_findings_shared" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "oscar_searched_logs" },
        group: "help_oscar_logs",
      },
      {
        id: "auri_ls_data",
        description: "Check the handoff file sizes",
        check: { source: "storyFlag", key: "auri_listed_handoff" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "auri_check_todo",
        description: "Review Chen's pending tasks",
        check: { source: "storyFlag", key: "auri_read_todo" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "auri_use_head",
        description: "Preview the CSV headers",
        check: { source: "storyFlag", key: "auri_used_head" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "auri_use_tail",
        description: "Check the latest pipeline entries",
        check: { source: "storyFlag", key: "auri_used_tail" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "auri_use_wc",
        description: "Count the total records",
        check: { source: "storyFlag", key: "auri_used_wc" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "report_to_oscar",
        description: "Report access.log findings to Oscar",
        check: { source: "completedObjective", key: "oscar_access_reported" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "processing_tools_accepted" },
        group: "help_oscar_logs",
      },
      {
        id: "explore_jchen",
        description: "Investigate Jin Chen's files",
        check: { source: "storyFlag", key: "found_backup_files" },
        hidden: true,
        optional: true,
      },
      {
        id: "discover_tampering",
        description: "Discover the log discrepancies",
        check: { source: "storyFlag", key: "discovered_log_tampering" },
        hidden: true,
        prerequisite: "explore_jchen",
        optional: true,
        group: "explore_jchen",
      },
      {
        id: "find_directives",
        description: "Find the operational directives",
        check: { source: "storyFlag", key: "found_chip_directives" },
        hidden: true,
        prerequisite: "explore_jchen",
        optional: true,
        group: "explore_jchen",
      },
      {
        id: "investigate_ops_data",
        description: "Investigate Dana's broken dashboard",
        check: { source: "storyFlag", key: "read_ops_incidents" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "dana_ops_accepted" },
      },
      {
        id: "report_dana_ops",
        description: "Report findings to Dana",
        check: { source: "completedObjective", key: "dana_ops_reported" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "read_ops_incidents" },
      },

      // Quest 4: Olive's Power Tools (visible after returning home)
      {
        id: "olive_power_tools",
        description: "Olive's Power Tools",
        check: { source: "allVisibleChildren" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "olive_power_tools_read" },
      },
      {
        id: "olive_pt_grep",
        description: "Filter output with grep",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_grep_at_home" },
        visibleWhen: { source: "storyFlag", key: "olive_power_tools_read" },
        group: "olive_power_tools",
      },
      {
        id: "olive_pt_wc",
        description: "Count files with wc",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_wc_at_home" },
        visibleWhen: { source: "storyFlag", key: "used_grep_at_home" },
        group: "olive_power_tools",
      },
      {
        id: "olive_pt_redirect",
        description: "Save command output to a file",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_history_redirect" },
        visibleWhen: { source: "storyFlag", key: "used_wc_at_home" },
        group: "olive_power_tools",
      },
      {
        id: "olive_pt_sort_uniq",
        description: "Analyze data with sort + uniq",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_sort_uniq_home" },
        visibleWhen: { source: "storyFlag", key: "used_history_redirect" },
        group: "olive_power_tools",
      },
      {
        id: "olive_pt_find",
        description: "Find files by name pattern",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_find_home" },
        visibleWhen: { source: "storyFlag", key: "used_sort_uniq_home" },
        group: "olive_power_tools",
      },
    ],
  },
  {
    id: "chapter-3",
    title: "Getting the Hang of This",
    objectives: [
      {
        id: "update_system",
        description: "Update your system",
        check: { source: "storyFlag", key: "apt_upgraded" },
        optional: true,
      },
      {
        id: "ssh_to_work_day2",
        description: "SSH to NexaCorp to start your second day",
        check: { source: "storyFlag", key: "ssh_day2" },
      },
      // Quest: Fix the Broken Pipeline
      {
        id: "fix_pipeline_quest",
        description: "Fix the Broken Pipeline",
        check: { source: "allVisibleChildren" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "ssh_to_work_day2" },
      },
      {
        id: "read_auri_day2_morning",
        description: "Check Auri's message on Piper",
        check: { source: "completedObjective", key: "read_auri_day2_morning" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "ssh_to_work_day2" },
        group: "fix_pipeline_quest",
      },
      {
        id: "pull_day2_updates",
        description: "Pull the latest repo changes in the dev container",
        check: { source: "storyFlag", key: "pulled_day2_updates" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "read_auri_day2_morning" },
        group: "fix_pipeline_quest",
      },
      {
        id: "discover_test_failure",
        description: "Run dbt build and find the failing test",
        check: { source: "storyFlag", key: "dbt_test_failed_day2" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "pulled_day2_updates" },
        group: "fix_pipeline_quest",
      },
      {
        id: "investigate_null_data",
        description: "Investigate the NULL data with snow sql",
        check: { source: "storyFlag", key: "investigated_null_data" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "dbt_test_failed_day2" },
        group: "fix_pipeline_quest",
      },
      {
        id: "create_fix_branch",
        description: "Create a feature branch for your fix",
        check: { source: "storyFlag", key: "created_fix_branch" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "dbt_test_failed_day2" },
        group: "fix_pipeline_quest",
      },
      {
        id: "fix_the_model",
        description: "Fix rpt_campaign_performance.sql and verify with dbt build",
        check: { source: "storyFlag", key: "fixed_campaign_model" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "dbt_test_failed_day2" },
        group: "fix_pipeline_quest",
      },
      {
        id: "push_fix",
        description: "Push your fix to the remote",
        check: { source: "storyFlag", key: "pushed_fix_branch" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "fixed_campaign_model" },
        group: "fix_pipeline_quest",
      },
      {
        id: "report_to_auri",
        description: "Let Auri know the pipeline is fixed",
        check: { source: "storyFlag", key: "reported_fix_to_auri" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "pushed_fix_branch" },
        group: "fix_pipeline_quest",
      },
    ],
  },
];
