import { panesSplit } from "./panes-split";
import { panesGrid } from "./panes-grid";
import { panesCleanup } from "./panes-cleanup";
import { panesResize } from "./panes-resize";
import { panesResizeRows } from "./panes-resize-rows";
import { panesResizeCorner } from "./panes-resize-corner";
import { windowsCreate } from "./windows-create";
import { gitFirstCommit } from "./git-first-commit";
import { gitUnstage } from "./git-unstage";
import { gitStashChallenge } from "./git-stash";
import { gitPullFf } from "./git-pull-ff";
import { gitRebaseChallenge } from "./git-rebase";
import { rmBomb } from "./rm-bomb";
import { chmodPerms } from "./chmod-perms";
import { mvOrganize } from "./mv-organize";
import { envExport } from "./env-export";
import { aliasShortcut } from "./alias-shortcut";
import { copyModeYank } from "./copy-mode-yank";
import { sessionsDetachAttach } from "./sessions-detach-attach";
import { sessionsJuggle } from "./sessions-juggle";
import { vimFirstEdit } from "./vim-first-edit";
import { vimDeleteLines } from "./vim-delete-lines";
import { vimFixWord } from "./vim-fix-word";
import { vimYankPaste } from "./vim-yank-paste";
import { vimSearchFix } from "./vim-search-fix";
import { vimReorder } from "./vim-reorder";
import type { Challenge } from "./types";

/** Ordered, linear progression. The player advances one challenge at a time. */
export const CHALLENGES: Challenge[] = [panesSplit, panesGrid, panesCleanup, panesResize, panesResizeRows, panesResizeCorner, windowsCreate, gitFirstCommit, gitUnstage, gitStashChallenge, gitPullFf, gitRebaseChallenge, rmBomb, chmodPerms, mvOrganize, envExport, aliasShortcut, copyModeYank, sessionsDetachAttach, sessionsJuggle, vimFirstEdit, vimDeleteLines, vimFixWord, vimYankPaste, vimSearchFix, vimReorder];
