export const HOME_PATHS = {
  resume: (u: string) => `/home/${u}/Downloads/resume_final_v3.pdf`,
  downloadsDir: (u: string) => `/home/${u}/Downloads`,
  zoomDeb: (u: string) => `/home/${u}/Downloads/zoom_amd64.deb`,
  pipDeb: (u: string) => `/home/${u}/Downloads/python3-pip_24.0+dfsg-1_all.deb`,
  jobJd: (u: string) => `/home/${u}/Downloads/NexaCorp_AI_Engineer_JD.pdf`,
  projectsDir: (u: string) => `/home/${u}/Projects`,
  backupLog: (u: string) => `/home/${u}/backup.log`,
  backupsScripts: (u: string) => `/home/${u}/backups/scripts/backup.sh`,
  backupsDir: (u: string) => `/home/${u}/backups`,
  dbtProject: (u: string) => `/home/${u}/nexacorp-analytics`,
  dbtDimEmployees: (u: string) => `/home/${u}/nexacorp-analytics/models/marts/dim_employees.sql`,
  dbtFctTickets: (u: string) => `/home/${u}/nexacorp-analytics/models/marts/fct_support_tickets.sql`,
  jobSearchLog: (u: string) => `/home/${u}/job_search_log.txt`,
  myCommandsTxt: (u: string) => `/home/${u}/my_commands.txt`,
} as const;

export const CHIPINFRA_PATHS = {
  chipPluginRegistry: "/opt/chip/plugins/registry.json",
  erikSocketDir: "/tmp/ssh-mZ4xPq",
  erikSocketMarker: "/tmp/ssh-mZ4xPq/.user-erik",
  erikAgentSocket: "/tmp/ssh-mZ4xPq/agent.18472",
} as const;

export const NEXACORP_PATHS = {
  accessLog: "/var/log/access.log",
  systemLog: "/var/log/system.log",
  systemLogBak: "/var/log/system.log.bak",
  authLogBak: "/var/log/auth.log.bak",
  chipPluginSdk: "/opt/chip/plugins/README.md",
  chipCleanup: "/opt/chip/plugins/log-maintenance/cleanup.sh",
  chipTicketTriage: "/opt/chip/plugins/ticket-triage/SKILL.md",
  chipSystemMonitor: "/opt/chip/plugins/system-monitor/SKILL.md",
  chipAlertRouting: "/opt/chip/plugins/alert-routing/SKILL.md",
  chipAnalyticsReports: "/opt/chip/plugins/analytics-reports/SKILL.md",
  chipLogMaintenance: "/opt/chip/plugins/log-maintenance/SKILL.md",
  onboarding: "/srv/engineering/onboarding.md",
  teamInfo: "/srv/engineering/team-info.md",
  chenHandoff: "/srv/engineering/chen-handoff",
  chenHandoffTodo: "/srv/engineering/chen-handoff/todo.txt",
  handoffNotes: "/srv/engineering/chen-handoff/notes.txt",
  pipelineRuns: "/srv/engineering/chen-handoff/pipeline_runs.csv",
  opsIncidents: "/srv/operations/ops_incidents.csv",
  boardMinutes: "/srv/leadership/board/2026-02-board-deck.md",
  headcountPlan: "/srv/leadership/finance/headcount_plan.csv",
  chipSessionsDir: (u: string) => `/home/${u}/.chip/sessions`,
} as const;
