import { ChapterDefinition } from "../engine/narrative/types";

export const CHAPTERS: ChapterDefinition[] = [
  {
    id: "chapter-1",
    title: "The Offer",
    objectives: [
      {
        id: "explore_home",
        description: "Explore your personal files",
        check: { source: "storyFlag", key: "read_resume" },
        optional: true,
      },
      {
        id: "learn_linux_basics",
        description: "Learn basic Linux commands",
        check: { source: "storyFlag", key: "basic_tools_unlocked" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "basic_tools_unlocked" },
        optional: true,
      },
      {
        id: "fix_backup",
        description: "Fix the backup script",
        check: { source: "storyFlag", key: "fixed_backup_script" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_backup_failure" },
        optional: true,
      },
      {
        id: "run_auto_apply",
        description: "Run the job application script",
        check: { source: "storyFlag", key: "ran_auto_apply" },
        optional: true,
      },
      {
        id: "check_email",
        description: "Check your email",
        check: { source: "storyFlag", key: "read_nexacorp_offer" },
      },
      {
        id: "check_piper",
        description: "Check Piper for messages",
        check: { source: "completedObjective", key: "piper_checked" },
        optional: true,
      },
      {
        id: "accept_offer",
        description: "Accept the job offer",
        check: { source: "completedObjective", key: "accepted_nexacorp" },
        failCheck: { source: "completedObjective", key: "rejected_nexacorp_final" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_nexacorp_offer" },
      },
      {
        id: "read_chip_setup",
        description: "Read Chip's setup email",
        check: { source: "storyFlag", key: "ssh_unlocked" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "accepted_nexacorp" },
      },
      {
        id: "first_ssh_connect",
        description: "SSH into NexaCorp to start work",
        check: { source: "storyFlag", key: "first_ssh_connect" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "ssh_unlocked" },
      },

      // Quest 1: Olive's Terminal Challenges
      {
        id: "olive_challenges",
        description: "Olive's Terminal Challenges",
        check: { source: "allVisibleChildren" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "olive_challenges_read" },
      },
      {
        id: "olive_ch_file",
        description: "Identify a file type with file",
        check: { source: "storyFlag", key: "used_file_in_downloads" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "olive_challenges_read" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_which",
        description: "Find where Python lives",
        check: { source: "storyFlag", key: "used_which_python" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "used_file_in_downloads" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_projects",
        description: "Create a Projects folder",
        check: { source: "storyFlag", key: "created_projects_dir" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "used_which_python" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_mv",
        description: "Rename a file with mv",
        check: { source: "storyFlag", key: "used_mv_home" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "created_projects_dir" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_echo",
        description: "Pipe or redirect echo output",
        check: { source: "storyFlag", key: "used_echo_pipe" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "used_mv_home" },
        group: "olive_challenges",
      },
      {
        id: "olive_ch_man",
        description: "Read a manual page",
        check: { source: "storyFlag", key: "used_man_command" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "used_echo_pipe" },
        group: "olive_challenges",
      },

      // Quest 2: Fix & Extend Backup
      {
        id: "backup_quest",
        description: "Fix & Extend Backup",
        check: { source: "allVisibleChildren" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
      },
      {
        id: "backup_mkdir",
        description: "Create a backup directory",
        check: { source: "storyFlag", key: "created_backups_dir" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
        group: "backup_quest",
      },
      {
        id: "backup_copy",
        description: "Copy your scripts to the backup",
        check: { source: "storyFlag", key: "copied_scripts_backup" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
        group: "backup_quest",
      },
      {
        id: "backup_log",
        description: "Log the backup result",
        check: { source: "storyFlag", key: "created_backup_log" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
        group: "backup_quest",
      },
      {
        id: "backup_verify",
        description: "Verify the backup with file",
        check: { source: "storyFlag", key: "verified_backup" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "backup_quest_started" },
        group: "backup_quest",
      },
    ],
  },
  {
    id: "chapter-2",
    title: "Onboarding",
    objectives: [
      {
        id: "read_welcome_email",
        description: "Read Edward's welcome email",
        check: { source: "storyFlag", key: "piper_unlocked" },
      },
      {
        id: "edward_onboarding",
        description: "Edward's Onboarding",
        check: { source: "allVisibleChildren" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "read_welcome_email" },
      },
      {
        id: "read_onboarding",
        description: "Read the onboarding docs",
        check: { source: "storyFlag", key: "read_onboarding" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "read_welcome_email" },
        group: "edward_onboarding",
      },
      {
        id: "meet_the_team",
        description: "Read the team directory",
        check: { source: "storyFlag", key: "read_team_info" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "read_welcome_email" },
        group: "edward_onboarding",
      },
      {
        id: "reply_edward_chip_intro",
        description: "Reply to Edward on Piper",
        check: { source: "completedObjective", key: "replied_edward_chip_intro" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_team_info" },
        group: "edward_onboarding",
      },
      {
        id: "try_chip",
        description: "Try running Chip",
        check: { source: "storyFlag", key: "chip_error_seen" },
        hidden: true,
        visibleWhen: {
          source: "all",
          checks: [
            { source: "storyFlag", key: "read_onboarding" },
            { source: "storyFlag", key: "read_team_info" },
            { source: "storyFlag", key: "chip_unlocked" },
          ],
        },
        group: "edward_onboarding",
      },
      {
        id: "tell_edward_chip_error",
        description: "Message Edward about the error",
        check: { source: "completedObjective", key: "told_edward_chip_error" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "chip_error_seen" },
        group: "edward_onboarding",
      },
      {
        id: "source_zshrc",
        description: "Set CHIP_API_KEY in your environment",
        check: { source: "storyFlag", key: "sourced_nexacorp_zshrc" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "printenv_unlocked" },
        group: "edward_onboarding",
      },
      {
        id: "help_oscar_logs",
        description: "Help Oscar with logs",
        check: { source: "completedObjective", key: "oscar_access_reported" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_onboarding" },
      },
      {
        id: "meet_auri",
        description: "Meet Auri",
        check: { source: "completedObjective", key: "auri_dbt_reported" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "piper_unlocked" },
      },
{
        id: "review_handoff",
        description: "Review Jin Chen's handoff notes",
        check: { source: "storyFlag", key: "read_handoff_notes" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "reply_auri_handoff",
        description: "Message Auri about the handoff notes",
        check: { source: "completedObjective", key: "handoff_reviewed" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_handoff_notes" },
        group: "meet_auri",
      },
      {
        id: "help_auri_pipeline",
        description: "Get familiar with the data pipeline",
        check: { source: "storyFlag", key: "ran_dbt" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "handoff_reviewed" },
        group: "meet_auri",
      },
      {
        id: "clone_analytics_repo",
        description: "Clone nexacorp-analytics",
        check: { source: "storyFlag", key: "dbt_project_cloned" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "help_auri_pipeline" },
        group: "meet_auri",
      },
      {
        id: "run_dbt",
        description: "Run a full pipeline build",
        check: { source: "storyFlag", key: "ran_dbt" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "clone_analytics_repo" },
        group: "meet_auri",
      },
      {
        id: "check_auri_dbt",
        description: "Check in with Auri about the build",
        check: { source: "completedObjective", key: "auri_dbt_reported" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "run_dbt" },
        group: "meet_auri",
      },
      // Closing Time quest group
      {
        id: "closing_time",
        description: "Closing Time",
        check: { source: "allVisibleChildren" },
        hidden: true,
        visibleWhen: { source: "deliveredEmail", key: "edward_end_of_day" },
      },
      {
        id: "read_eod_email",
        description: "Read Edward's end-of-day email",
        check: { source: "storyFlag", key: "read_end_of_day" },
        hidden: true,
        visibleWhen: { source: "deliveredEmail", key: "edward_end_of_day" },
        group: "closing_time",
      },
      {
        id: "head_home",
        description: "Head home for the day",
        check: { source: "storyFlag", key: "returned_home_day1" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_end_of_day" },
        group: "closing_time",
      },
      {
        id: "read_piper_home",
        description: "Read your Piper messages at home",
        check: { source: "storyFlag", key: "read_piper_day1_home" },
        optional: true,
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "returned_home_day1" },
      },
      {
        id: "shutdown_day1",
        description: "Shut down your PC",
        check: { source: "storyFlag", key: "day1_shutdown" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "returned_home_day1" },
        group: "closing_time",
      },
      {
        id: "oscar_search_logs",
        description: "Search the system logs for errors",
        check: { source: "storyFlag", key: "oscar_searched_logs" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
        group: "help_oscar_logs",
      },
      {
        id: "oscar_check_backups",
        description: "Check the backup logs",
        check: { source: "storyFlag", key: "oscar_checked_backups" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
        group: "help_oscar_logs",
      },
      {
        id: "oscar_diff_logs",
        description: "Diff the active and backup logs",
        check: { source: "storyFlag", key: "oscar_diffed_logs" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
        group: "help_oscar_logs",
      },
      {
        id: "reply_oscar_logs",
        description: "Report system log findings to Oscar",
        check: { source: "completedObjective", key: "oscar_log_findings_shared" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "oscar_searched_logs" },
        group: "help_oscar_logs",
      },
      {
        id: "auri_ls_data",
        description: "Check the handoff file sizes",
        check: { source: "storyFlag", key: "auri_listed_handoff" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "auri_check_todo",
        description: "Review Chen's pending tasks",
        check: { source: "storyFlag", key: "auri_read_todo" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "auri_use_head",
        description: "Preview the CSV headers",
        check: { source: "storyFlag", key: "auri_used_head" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "auri_use_tail",
        description: "Check the latest pipeline entries",
        check: { source: "storyFlag", key: "auri_used_tail" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "auri_use_wc",
        description: "Count the total records",
        check: { source: "storyFlag", key: "auri_used_wc" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
        group: "meet_auri",
      },
      {
        id: "report_to_oscar",
        description: "Report access.log findings to Oscar",
        check: { source: "completedObjective", key: "oscar_access_reported" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "processing_tools_accepted" },
        group: "help_oscar_logs",
      },
      {
        id: "explore_jchen",
        description: "Investigate Jin Chen's files",
        check: { source: "storyFlag", key: "found_backup_files" },
        hidden: true,
        optional: true,
      },
      {
        id: "discover_tampering",
        description: "Discover the log discrepancies",
        check: { source: "storyFlag", key: "discovered_log_tampering" },
        hidden: true,
        prerequisite: "explore_jchen",
        optional: true,
        group: "explore_jchen",
      },
      {
        id: "find_directives",
        description: "Find the operational directives",
        check: { source: "storyFlag", key: "found_chip_directives" },
        hidden: true,
        prerequisite: "explore_jchen",
        optional: true,
        group: "explore_jchen",
      },
      {
        id: "investigate_ops_data",
        description: "Investigate Dana's broken dashboard",
        check: { source: "storyFlag", key: "read_ops_incidents" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "dana_ops_accepted" },
      },
      {
        id: "report_dana_ops",
        description: "Report findings to Dana",
        check: { source: "completedObjective", key: "dana_ops_reported" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "read_ops_incidents" },
      },

      // Quest: Jordan's Marketing Data
      {
        id: "jordan_query_metrics",
        description: "Query campaign_metrics in Snowflake",
        check: { source: "storyFlag", key: "found_inflated_metrics" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "pipeline_tools_accepted" },
      },
      {
        id: "jordan_report_findings",
        description: "Report findings to Jordan on Piper",
        check: { source: "completedObjective", key: "jordan_metrics_reported" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "found_inflated_metrics" },
      },

      // Quest 4: Olive's Power Tools (visible after returning home)
      {
        id: "olive_power_tools",
        description: "Olive's Power Tools",
        check: { source: "allVisibleChildren" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "olive_power_tools_read" },
      },
      {
        id: "olive_pt_grep",
        description: "Filter output with grep",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_grep_at_home" },
        visibleWhen: { source: "storyFlag", key: "olive_power_tools_read" },
        group: "olive_power_tools",
      },
      {
        id: "olive_pt_wc",
        description: "Count files with wc",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_wc_at_home" },
        visibleWhen: { source: "storyFlag", key: "used_grep_at_home" },
        group: "olive_power_tools",
      },
      {
        id: "olive_pt_redirect",
        description: "Save command output to a file",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_history_redirect" },
        visibleWhen: { source: "storyFlag", key: "used_wc_at_home" },
        group: "olive_power_tools",
      },
      {
        id: "olive_pt_sort_uniq",
        description: "Analyze data with sort + uniq",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_sort_uniq_home" },
        visibleWhen: { source: "storyFlag", key: "used_history_redirect" },
        group: "olive_power_tools",
      },
      {
        id: "olive_pt_find",
        description: "Find files by name pattern",
        hidden: true,
        optional: true,
        check: { source: "storyFlag", key: "used_find_home" },
        visibleWhen: { source: "storyFlag", key: "used_sort_uniq_home" },
        group: "olive_power_tools",
      },
    ],
  },
  {
    id: "chapter-3",
    title: "In Production",
    objectives: [
      {
        id: "update_system",
        description: "Update your system",
        check: { source: "storyFlag", key: "apt_upgraded" },
        optional: true,
      },
      {
        id: "ssh_to_work_day2",
        description: "SSH to NexaCorp to start your second day",
        check: { source: "storyFlag", key: "ssh_day2" },
      },

      // Quest: Anonymous Tip — surfaces on Day 2 boot at home; introduces
      // mount/umount via the unknown-sender USB drop.
      {
        id: "anon_tip_quest",
        description: "Anonymous Tip",
        check: { source: "allVisibleChildren" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "anon_tip_quest_started" },
      },
      {
        id: "anon_tip_check_piper",
        description: "Check your Piper messages at home",
        check: { source: "storyFlag", key: "anon_tip_dm_resolved" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "anon_tip_quest_started" },
        group: "anon_tip_quest",
      },
      {
        id: "anon_tip_lsblk",
        description: "List block devices to find the drive",
        check: { source: "storyFlag", key: "ran_lsblk_for_usb" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "accepted_usb_drive" },
        group: "anon_tip_quest",
      },
      {
        id: "anon_tip_mount",
        description: "Mount the drive at /mnt/usb",
        check: { source: "storyFlag", key: "mounted_usb_drive" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "ran_lsblk_for_usb" },
        group: "anon_tip_quest",
      },
      {
        id: "anon_tip_read",
        description: "Read the note on the drive",
        check: { source: "storyFlag", key: "read_usb_note" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "mounted_usb_drive" },
        group: "anon_tip_quest",
      },
      // Quest: Fix the Broken Pipeline
      {
        id: "fix_pipeline_quest",
        description: "Fix the Broken Pipeline",
        check: { source: "allVisibleChildren" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "ssh_to_work_day2" },
      },
      {
        id: "read_auri_day2_morning",
        description: "Check Auri's message on Piper",
        check: { source: "completedObjective", key: "read_auri_day2_morning" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "ssh_to_work_day2" },
        group: "fix_pipeline_quest",
      },
      {
        id: "pull_day2_updates",
        description: "Pull the latest repo changes in the dev container",
        check: { source: "storyFlag", key: "pulled_day2_updates" },
        hidden: true,
        visibleWhen: { source: "completedObjective", key: "read_auri_day2_morning" },
        group: "fix_pipeline_quest",
      },
      {
        id: "discover_test_failure",
        description: "Run dbt build and find the failing test",
        check: { source: "storyFlag", key: "dbt_test_failed_day2" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "pulled_day2_updates" },
        group: "fix_pipeline_quest",
      },
      {
        id: "investigate_null_data",
        description: "Investigate the NULL data with snow sql",
        check: { source: "storyFlag", key: "investigated_null_data" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "dbt_test_failed_day2" },
        group: "fix_pipeline_quest",
      },
      {
        id: "create_fix_branch",
        description: "Create a feature branch for your fix",
        check: { source: "storyFlag", key: "created_fix_branch" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "dbt_test_failed_day2" },
        group: "fix_pipeline_quest",
      },
      {
        id: "fix_the_model",
        description: "Fix rpt_campaign_performance.sql and verify with dbt build",
        check: { source: "storyFlag", key: "fixed_campaign_model" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "dbt_test_failed_day2" },
        group: "fix_pipeline_quest",
      },
      {
        id: "push_fix",
        description: "Push your fix to the remote",
        check: { source: "storyFlag", key: "pushed_fix_branch" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "fixed_campaign_model" },
        group: "fix_pipeline_quest",
      },
      {
        id: "report_to_auri",
        description: "Let Auri know the pipeline is fixed",
        check: { source: "storyFlag", key: "reported_fix_to_auri" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "pushed_fix_branch" },
        group: "fix_pipeline_quest",
      },

      // Quest: Build a Chip plugin (investor-demo, gated by Edward's DM after pipeline fix)
      {
        id: "build_chip_plugin_quest",
        description: "Build a new Chip plugin",
        check: { source: "allVisibleChildren" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "reported_fix_to_auri" },
      },
      {
        id: "accepted_edward_plugin_request",
        description: "Reply to Edward in Piper",
        check: { source: "storyFlag", key: "unlock_chip_plugin_development" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "reported_fix_to_auri" },
        group: "build_chip_plugin_quest",
      },
      {
        id: "ssh_to_chip_workspace",
        description: "SSH into the Chip platform workspace (coder ssh chip)",
        check: { source: "storyFlag", key: "chipinfra_visited" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "unlock_chip_plugin_development" },
        group: "build_chip_plugin_quest",
      },
      {
        id: "read_existing_plugin",
        description: "Read an existing plugin to learn the format",
        check: { source: "storyFlag", key: "read_plugin_template" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "chipinfra_visited" },
        group: "build_chip_plugin_quest",
      },
      {
        id: "create_plugin_dir",
        description: "Create your plugin directory at /opt/chip/plugins/<plugin-name>/",
        check: { source: "storyFlag", key: "created_chip_plugin_dir" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "chipinfra_visited" },
        group: "build_chip_plugin_quest",
      },
      {
        id: "write_plugin_manifest",
        description: "Write plugin.json with the plugin's metadata",
        check: { source: "storyFlag", key: "wrote_plugin_manifest" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "created_chip_plugin_dir" },
        group: "build_chip_plugin_quest",
      },
      {
        id: "write_plugin_skill",
        description: "Write SKILL.md describing what the plugin does",
        check: { source: "storyFlag", key: "wrote_plugin_skill" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "created_chip_plugin_dir" },
        group: "build_chip_plugin_quest",
      },
      {
        id: "register_plugin",
        description: "Register your plugin in /opt/chip/plugins/registry.json",
        check: { source: "storyFlag", key: "registered_chip_plugin" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "wrote_plugin_manifest" },
        group: "build_chip_plugin_quest",
      },
      {
        id: "report_plugin_to_edward",
        description: "Tell Edward your plugin is ready",
        check: { source: "storyFlag", key: "reported_plugin_to_edward" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "wrote_plugin_skill" },
        group: "build_chip_plugin_quest",
      },

      // Quest: Pulling at a Loose Thread — opens once the player has both
      // read the USB note (at home) and visited chipinfra. Children walk
      // the existing SSH-agent-forwarding pivot to Erik's PC.
      {
        id: "loose_thread_quest",
        description: "Pulling at a Loose Thread",
        check: { source: "allVisibleChildren" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "loose_thread_quest_started" },
      },
      {
        id: "loose_thread_find_socket",
        description: "Find the stale ssh agent socket (/tmp)",
        check: { source: "storyFlag", key: "cat_erik_socket_marker" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "loose_thread_quest_started" },
        group: "loose_thread_quest",
      },
      {
        id: "loose_thread_export_sock",
        description: "Point your shell at Erik's ssh-agent socket",
        check: { source: "storyFlag", key: "exported_erik_ssh_auth_sock" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "cat_erik_socket_marker" },
        group: "loose_thread_quest",
      },
      {
        id: "loose_thread_inspect_keys",
        description: "Inspect the forwarded ssh keys",
        check: { source: "storyFlag", key: "ran_ssh_add_erik" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "exported_erik_ssh_auth_sock" },
        group: "loose_thread_quest",
      },
      {
        id: "loose_thread_pivot",
        description: "Pivot to Erik's laptop",
        check: { source: "storyFlag", key: "pivoted_to_erik_pc" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "ran_ssh_add_erik" },
        group: "loose_thread_quest",
      },
      // Optional cover-tracks step. The pivot wrote a nexacorp-lt05 entry into
      // chipinfra's ~/.ssh/known_hosts; leaving it there triggers the
      // hr_security_freeze email at home. `rm` the file before logoff to
      // suppress the email and tick this objective. Other scrubs (nano edit,
      // `>` truncate) also suppress the email but won't tick the objective.
      {
        id: "loose_thread_cover_tracks",
        description: "Cover your tracks: remove ~/.ssh/known_hosts on chipinfra",
        check: { source: "storyFlag", key: "cleared_erik_known_hosts" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "storyFlag", key: "pivoted_to_erik_pc" },
        group: "loose_thread_quest",
      },

      // Quest: Marcus's Accusation (Chapter 3 endgame). Opens once the
      // required plugin quest closes. The four `accused_*` carrier flags
      // persist into Chapter 4 so the board-meeting scene can branch on
      // the player's pick.
      {
        id: "marcus_endgame_quest",
        description: "Before the Board Meeting",
        check: { source: "allVisibleChildren" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "reported_plugin_to_edward" },
      },
      {
        id: "accuse_chip_abuser",
        description: "Tell Marcus who you think is abusing Chip's access",
        check: { source: "storyFlag", key: "accusation_made" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "reported_plugin_to_edward" },
        group: "marcus_endgame_quest",
      },
      {
        id: "chapter_3_finale",
        description: "Acknowledge Marcus before he heads into the board meeting",
        check: { source: "storyFlag", key: "chapter_3_complete" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "accusation_made" },
        group: "marcus_endgame_quest",
      },
      // Wrap-up: `exit` from NexaCorp post-accusation auto-opens Marcus's
      // branched debrief in `less` and transitions home on q. Fires the
      // synthetic `read_board_debrief` event from exit.ts → sets
      // read_board_debrief_day2 (see storyFlags.ts). Closing this objective
      // closes the marcus_endgame_quest group and ends Chapter 3.
      {
        id: "head_home_day2",
        description: "Head home, the day's done",
        check: { source: "storyFlag", key: "read_board_debrief_day2" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "accusation_made" },
        group: "marcus_endgame_quest",
      },
    ],
  },
];
